### ISSUE TITLE
Use EZButton in a simple library

### ISSUE THREAD

**Issue by ChristianKniep** [IPdotSetAF/EZButton#12]
I'd like to create a simple library to externalise the code of buttonpress and such. The goal is to tidy up the code of a ButtonBox for a simulator. So when I press a button on the box, it will most likely press a Keyboard combo so that something happens in the simulation (DCS,MSFS, RaceSim).

What I came up with so far looks something like this - but I am struggling to define the button(s) within my custom library.

```cpp 
/* file: Button.h */


#ifndef BUTTON_H
#define BUTTON_H

#include <Arduino.h>
#include <ezButton.h>

class ButtonInputAction {
  
  private:
    EZButton ezb;
    int pin;                // Analog pin number (A0, A1, A2, etc.)
    bool prev;          // Previous state of the button (might not be needed here)
    bool start;          // Did I already read the button (also not needed but I keep it for completnes sake)
    String description;  // Message that should be send on press/release to have a log of what is going on
    uint8_t mod;      // Key (from Keyboard.h) to be pressed, like KEYL_LEFT_ALT
    char pressed;    // Actual key pressed when the button is pressed
    char released;   // key pressed when the button is released

    
  public:
    // Setup Button
    ButtonInputAction(int pin, String desc, uint8_t mod, char pressed, char released);

    // Setup
    void init();
    
    // Check
    void check();
};

#endif
```
```cpp 
/* file: Button.cpp */

#include "Button.h"
#include <EZButton.h>


//EZButton but;
EZButton _ezb;

ButtonInputAction::ButtonInputAction(int size, String desc, uint8_t mod, char pressed, char released) {
  _ezb(4, ReadButtons, 500, 300);
  this->pin = pin;
  this->prev = false;
  this->start = false;
  this->description = desc;
  this->mod = mod;
  this->pressed = pressed;
  this->released = released;
  init();
}

void ButtonInputAction::init() {
  but.setDebounceTime(50);
  
}

void ButtonInputAction::check() {
  but.loop();
  bool curState = but.getState() == 1;
  if (!start) {
    prev = curState;
    start = true;
    return;
  }
  
  if (curState != prev) {
    // State changed
    prev = curState;
    if (curState) {
      // Pressed
      String msg = String(String(description) + " pressed");
    } else {
      // Released
      String msg = String(String(description) + " released");
    }
  }
}
```

**Comment by IPdotSetAF** [comment]
hey @ChristianKniep .

seems like you did not follow the provided example.
here are a few tips and what you are missing in your code:

1. why do you have multiple EZButton instances, you only need one!

> ```c++
> EZButton ezb;
> ```

> ```c++
> EZButton _ezb;
> ```

2. you did not construct the object properly.
3. you don't need any other properties for reading and debouncing the buttons as the library handles them all.
4. you must call the subscribe() function of the EZButton for any event that you need to bind to a button action.
```c++
_ezb.Subscribe(0, Btn1Pressed, PRESSED);
```
```
void Btn1Pressed(){
  //do the pressed action
}
```
5. you need to define the `ReadButtons()` function to read button state from the pin, there is no need for debouncing just follow the example.
6. call ` _ezb.Loop();` in your `loop()` function.

example: https://github.com/IPdotSetAF/EZButton/blob/main/examples/Blink/Blink.ino

ps: if you need debouncing feature you can open another issue, to implement it later on or open a pull request adding the feature to the main library.

**Comment by ChristianKniep** [comment]
The simple example is working, indeed. My question is about how I would do that within an custom library.

**Comment by IPdotSetAF** [comment]
Depends on your needs and what u need to modify.

You can pass in an already created instance of EZButton as input to the init function of your Library and do what you want to do.

Or you might need to extend its class and have more access to the internal variables and functions.
