### ISSUE TITLE
Bug: Example sketch should use INPUT_PULLUP instead of the currently used INPUT

### ISSUE THREAD

**Issue by erikgk** [IPdotSetAF/EZButton#6]
https://github.com/IPdotSetAF/EZButton/blob/bc16ed4d70b627d0220e850cfa0ccc9e652efa33/examples/Blink/Blink.ino#L15

See this mentioned line. Is it intentionally INPUT in this example sketch instead of the better INPUT_PULLUP?

**Comment by IPdotSetAF** [comment]
> https://github.com/IPdotSetAF/EZButton/blob/bc16ed4d70b627d0220e850cfa0ccc9e652efa33/examples/Blink/Blink.ino#L15
> 
> See this mentioned line. Is it intentionally INPUT in this example sketch instead of the better INPUT_PULLUP?

Well The board that i was testing the sketch with (a chinese Arduino Nano) had some issues with the `INPUT_PULLUP` or maybe it was my bug at that moment, I will check again.

**Comment by erikgk** [comment]
Thank you!
